"""empty message

Revision ID: 1e208a18c311
Revises: 7739859ee498
Create Date: 2020-02-12 14:51:04.178364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e208a18c311'
down_revision = '7739859ee498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comments', 'pitches', ['pitch_id'], ['id'])
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    # ### end Alembic commands ###
