"""empty message

Revision ID: 6318189dcdb5
Revises: 76e969651ce1
Create Date: 2020-02-10 12:00:35.271510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6318189dcdb5'
down_revision = '76e969651ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
